// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"go-zero-learning/backend/app/demo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/item/:id",
				Handler: GetItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/item/:id",
				Handler: UpdateItemHandler(serverCtx),
			},
		},
		rest.WithPrefix("/demo"),
	)
}
