// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: identity.proto

package identity

import (
	"context"

	"go-zero-learning/backend/app/identity/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserReq  = pb.GetUserReq
	GetUserResp = pb.GetUserResp

	Identity interface {
		// 定义一个 RPC 方法：传入 GetUserReq，返回 GetUserResp
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
	}

	defaultIdentity struct {
		cli zrpc.Client
	}
)

func NewIdentity(cli zrpc.Client) Identity {
	return &defaultIdentity{
		cli: cli,
	}
}

// 定义一个 RPC 方法：传入 GetUserReq，返回 GetUserResp
func (m *defaultIdentity) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := pb.NewIdentityClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
