// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: identity.proto

package server

import (
	"context"

	"go-zero-learning/backend/app/identity/rpc/internal/logic"
	"go-zero-learning/backend/app/identity/rpc/internal/svc"
	"go-zero-learning/backend/app/identity/rpc/pb"
)

type IdentityServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIdentityServer
}

func NewIdentityServer(svcCtx *svc.ServiceContext) *IdentityServer {
	return &IdentityServer{
		svcCtx: svcCtx,
	}
}

// 定义一个 RPC 方法：传入 GetUserReq，返回 GetUserResp
func (s *IdentityServer) GetUser(ctx context.Context, in *pb.GetUserReq) (*pb.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
