syntax = "proto3";

// 1. 定义包名 (相当于 Go 的 package)
package identity;

// 指定 Go 语言生成路径为模块路径下的 pb 包
option go_package = "go-zero-learning/backend/app/identity/rpc/pb;pb";

// 根据 ID 获取用户信息
message GetUserReq {
  int64 id = 1;
}

message GetUserResp {
  int64 id = 1;
  string username = 2;
}

// 创建用户（注册）
message CreateUserReq {
  string username = 1;
  string password = 2;
}

message CreateUserResp {
  int64 id = 1;
  string username = 2;
}

service Identity {
  rpc GetUser(GetUserReq) returns (GetUserResp);
  rpc CreateUser(CreateUserReq) returns (CreateUserResp);
}
