// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetItemReq struct {
	Id int64 `path:"id"`
}

type ItemResp struct {
	Id        int64
	Name      string
	UpdatedAt string
}

type UpdateItemReq struct {
	Id   int64  `path:"id"`
	Name string `json:"name"`
}
